Remove 'petl' from requirements.txt
This project doesn't appear to be pyproject.toml-based anymore, if
indeed it ever was -- nothing here seems to use 'petl' currently.

Meanwhile, the petl req was causing 'pip install -r requirements.txt'
to fail with the following error (which, though long, I will paste
much of below in case you're searching for it later in commit logs):

  $ pip install -r requirements.txt
  Defaulting to user installation because normal site-packages is not writeable
  Requirement already satisfied: Click>=7.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (8.0.3)
  Requirement already satisfied: fuzzywuzzy==0.18.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.18.0)
  Requirement already satisfied: py-moneyed==0.8.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.8.0)
  Collecting PyYAML==5.3
    Using cached PyYAML-5.3-cp310-cp310-linux_x86_64.whl
  Requirement already satisfied: python-Levenshtein in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (0.12.2)
  Collecting petl
    Using cached petl-1.7.9.tar.gz (407 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
  Building wheels for collected packages: petl
    Building wheel for petl (pyproject.toml) ... error
    error: subprocess-exited-with-error

    × Building wheel for petl (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [2138 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib
        creating build/lib/petl
        copying ./petl/__init__.py -> build/lib/petl
        [...many lines omitted...]
        copying ./petl/test/util/test_materialise.py -> build/lib/petl/test/util
        running build_scripts
        creating build/scripts-3.10
        running install
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
            return self._build_with_temp_dir(['bdist_wheel'], '.whl',
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
            self.run_setup()
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 5, in <module>
            setup(
          File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
            self.run_command('install')
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
            cmd_obj.ensure_finalized()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
            self.finalize_options()
          File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 45, in finalize_options
            orig.install.finalize_options(self)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 320, in finalize_options
            self.finalize_unix()
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 59, in finalize_unix
            super().finalize_unix()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 488, in finalize_unix
            self.select_scheme("posix_prefix")
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 55, in select_scheme
            super().select_scheme(name)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 522, in select_scheme
            scheme = _load_schemes()[name]
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 137, in wrapped_load_schemes
            _inject_headers(name, scheme)
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 125, in _inject_headers
            scheme['headers'] = orig_install._load_schemes()['posix_prefix']['headers']
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 137, in wrapped_load_schemes
            _inject_headers(name, scheme)
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 125, in _inject_headers
            scheme['headers'] = orig_install._load_schemes()['posix_prefix']['headers']
          File "/usr/lib/python3.10/_distutils_system_mod.py", line 137, in wrapped_load_schemes
            _inject_headers(name, scheme)
          [...many lines omitted...]
            schemes = _load_schemes()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 103, in _load_schemes
            sysconfig_schemes = _load_sysconfig_schemes() or {}
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 91, in _load_sysconfig_schemes
            with contextlib.suppress(AttributeError):
        RecursionError: maximum recursion depth exceeded
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for petl
  Failed to build petl
  ERROR: Could not build wheels for petl, which is required to install pyproject.toml-based projects
  $